version: "3.4"
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.43.0@sha256:79dfc89947410ec120a3e34cf68f746f6f154de20772e6f27b9998ca9bd65a5e
    container_name: plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    networks:
      - sofa-squad
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:4.0.16@sha256:21c1c3d52248589bb064f5adafec18cad45812d7a01d317472955eef051e619b
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    networks:
      - sofa-squad
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CONFIG_ROOT}/config/sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv
      - ${MEDIA_ROOT}/downloads:/downloads
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.28.0@sha256:c984533510abe0219a70e80d15bd0d212b7df21baa0913759c4ce6cc9092240b
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    networks:
      - sofa-squad
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CONFIG_ROOT}/config/radarr:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads
  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: linuxserver/overseerr:1.35.0@sha256:6108ed066d4a919c05251d9dab041c1e55e67ff7247e7b31be97b65ffcbaeeb1
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-swag
  swag:
    image: linuxserver/swag:5.4.0@sha256:0f323e1ffd3d449a567cea5ef9b385f1c428aa4a7cd064a4ce1866ddf538dfa5
    container_name: swag
    networks:
      - sofa-squad
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - VALIDATION=http
      - SUBDOMAINS=www,overseerr #optional
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - ${CONFIG_ROOT}/config/swag:/config
    ports:
      - 443:443
      - 80:80
      - 81:81
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:2.16.1@sha256:24594d6aed5f862f941349a6fa0d09d22d7a8386789aef954d3737c6b4dbb8c7
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/tautulli:/config
  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.5.6@sha256:05f9d5b24884f37120453dc1a008a47be244eebec32099ae1bd29032e75b67aa
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    ports:
      - 6767:6767
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/complete/tv:/tv
  # https://docs.linuxserver.io/images/docker-duckdns
  duckdns:
    image: linuxserver/duckdns:version-256b24bf@sha256:b9e271bf35238f7c843dd033a0c579dfb6b28f5a50b739cc4aba43e86bf0d586
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}
      - TOKEN=${DUCK_DNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ${CONFIG_ROOT}/config/duckdns:/config
    restart: unless-stopped
  # https://www.authelia.com/integration/deployment/docker
  authelia:
    container_name: authelia
    image: authelia/authelia:4.39@sha256:d23ee3c721d465b4749cc58541cda4aebe5aa6f19d7b5ce0afebb44ebee69591
    restart: unless-stopped
    networks:
      - sofa-squad
    expose:
      - 9091
    volumes:
      - ${CONFIG_ROOT}/config/authelia:/config
    environment:
      - TZ=${TZ}
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: linuxserver/sabnzbd:4.5.5@sha256:9b6662d5871518346655bfd3acb4c94e11f31c79c103ef04154558dab927c852
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${MEDIA_ROOT}/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - sofa-squad
  # https://recyclarr.dev/guide/installation/docker/
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8
    container_name: recyclarr
    user: ${PUID}:${PGID}
    restart: unless-stopped
    networks:
      - sofa-squad
    environment:
      - TZ=${TZ}
      - CRON_SCHEDULE=@daily
    volumes:
      - ${CONFIG_ROOT}/config/recyclarr:/config
networks:
  sofa-squad:
    name: sofa-squad
