version: "3.4"
services:
  # https://gethomepage.dev/installation/docker/
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_ROOT}:/media:ro
  # https://docs.maintainerr.info/Installation/
  maintainerr:
    container_name: maintainerr
    image: ghcr.io/maintainerr/maintainerr:3.10.1@sha256:afc7e45c3d32eeea32946420c592802e6daf33f222114ce54c4a086a53b9838e
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 6246:6246
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/maintainerr:/opt/data
  # https://docs.linuxserver.io/images/docker-lazylibrarian/
  lazylibrarian:
    container_name: lazylibrarian
    image: lscr.io/linuxserver/lazylibrarian:latest@sha256:6c8d11b3100153f1dfb23f030a2b5c7ea904230a3745eba69d31997c508f9970
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
    ports:
      - 5299:5299
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/lazylibrarian:/config
      - ${MEDIA_ROOT}/downloads:/downloads
      - ${MEDIA_ROOT}/complete/audiobooks:/books
  # https://www.audiobookshelf.org/docs
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest@sha256:4ac90a4f6669dfe6fd3aea2fedca2bb1eb8a758c16ac676f598b228c7d8da0f1
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 13378:80
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/audiobookshelf:/config
      - ${MEDIA_ROOT}/complete/audiobooks:/audiobooks
      - ${CONFIG_ROOT}/config/audiobookshelf/metadata:/metadata
networks:
  sofa-squad:
    external: true
