version: "3.4"
services:
  # https://gethomepage.dev/installation/docker/
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.12.1@sha256:9627769818fbfb14147d3e633e57cef9c27c0c5f07585f5a1d6c3d3425b3b33c
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_ROOT}:/media:ro
  # https://docs.maintainerr.info/Installation/
  maintainerr:
    container_name: maintainerr
    image: ghcr.io/maintainerr/maintainerr:3.3.0@sha256:918e375bf295f6a97ddfa0e6002b4b4b23adc47d118e54a8d0bbd4a4a5aa9bc8
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 6246:6246
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/maintainerr:/opt/data
  # https://docs.linuxserver.io/images/docker-lazylibrarian/
  lazylibrarian:
    container_name: lazylibrarian
    image: lscr.io/linuxserver/lazylibrarian:latest@sha256:facd8555a99cef5ce1f8ba8af1cbae472cc35d14aa1492e1b9c3b00f0b23951a
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
    ports:
      - 5299:5299
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/lazylibrarian:/config
      - ${MEDIA_ROOT}/downloads:/downloads
      - ${MEDIA_ROOT}/complete/audiobooks:/books
  # https://www.audiobookshelf.org/docs
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest@sha256:5a8a20c28e0193ab8b038623dd16d2f68f490c2544cc7debfe4658f42c71b3f9
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 13378:80
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/audiobookshelf:/config
      - ${MEDIA_ROOT}/complete/audiobooks:/audiobooks
      - ${CONFIG_ROOT}/config/audiobookshelf/metadata:/metadata
networks:
  sofa-squad:
    external: true
