version: "3.4"
services:
  # https://gethomepage.dev/installation/docker/
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_ROOT}:/media:ro
  # https://docs.maintainerr.info/Installation/
  maintainerr:
    container_name: maintainerr
    image: ghcr.io/maintainerr/maintainerr:3.7.0@sha256:bfc9d16c3f752e17432e5a66df5bbeb4c115698f9dd496ee03fd0aa9ef3dca52
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 6246:6246
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/maintainerr:/opt/data
  # https://docs.linuxserver.io/images/docker-lazylibrarian/
  lazylibrarian:
    container_name: lazylibrarian
    image: lscr.io/linuxserver/lazylibrarian:latest@sha256:c77097357b79116fb709e0844e75fb74263f098038df4c24aab1ec2cf98ec5f9
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
    ports:
      - 5299:5299
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/lazylibrarian:/config
      - ${MEDIA_ROOT}/downloads:/downloads
      - ${MEDIA_ROOT}/complete/audiobooks:/books
  # https://www.audiobookshelf.org/docs
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest@sha256:c4d1b5326c5134cf1f43e0835ac52948205dea5d242225cdc400ed5ff6a37915
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 13378:80
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/audiobookshelf:/config
      - ${MEDIA_ROOT}/complete/audiobooks:/audiobooks
      - ${CONFIG_ROOT}/config/audiobookshelf/metadata:/metadata
networks:
  sofa-squad:
    external: true
