name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version and commit message
      id: extract-info
      run: |
        cat version.txt
        version=$(cat version.txt)  # Replace with the path to your version file
        echo "::set-output name=version::$version"

    - name: Determine version increment
      id: increment-version
      run: |
        commit_description=$(git log --format=%B -n 1 ${{ github.sha }})
        major_version=$(echo ${{ steps.extract-info.outputs.version }} | awk -F'.' '{print $1}')
        minor_version=$(echo ${{ steps.extract-info.outputs.version }} | awk -F'.' '{print $2}')
        echo "Major"
        echo "$major_version"
        echo "Minor"
        echo "$minor_version"
        echo "Desccription"
        echo "$commit_description"
        if [[ $commit_description == *"major"* ]]; then
          echo "New major version"
          new_major_version=$((major_version + 1))
          new_version="$new_major_version.0"
        else
          echo "New minor version"
          new_minor_version=$(($minor_version + 1))
          echo "New minor version"
          new_version="$major_version.$new_minor_version"
        fi
        echo "New  version"
        echo "$new_version"
        echo "::set-output name=new_version::$new_version"

    - name: Update version.txt
      run: |
        echo "${{ steps.increment-version.outputs.new_version }}" > version.txt
        git config user.name "bcanfield"
        git config user.email "brandincanfield@gmail.com"
        git add version.txt

    - name: Update changelog.md
      run: |
        COMMIT_MESSAGE=$(git log --format=%s -n 1 ${{ github.sha }})
        echo "## v${{ steps.increment-version.outputs.new_version }}" >> changelog.md
        echo "- Change: $COMMIT_MESSAGE" >> changelog.md
        echo "" >> changelog.md
        git add changelog.md
        git commit -m "v${{ steps.increment-version.outputs.new_version }}"
        git push

    - name: Create Git Tag
      run: |
        git tag -a -m "v${{ steps.increment-version.outputs.new_version }}" v${{ steps.increment-version.outputs.new_version }}
        git push origin v${{ steps.increment-version.outputs.new_version }}

